[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bitcoin-decentralisation"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2",
    "numpy>=1.26",
    "pyarrow>=17.0",
    "matplotlib>=3.8",
]

[tool.setuptools.packages.find]
where = ["src"]
